### ISSUE TITLE
How can i reproduce the sota results

### ISSUE THREAD

**Issue by SLime1998** [Uason-Chen/CTR-GCN#10]
Hi! Thanks for sharing your excellent work. I trained the model using the given config file, but the result is not as good as in the paper. The performance on ntu60 cross-subject i got on joint stream is 89.52% which is worse than yours of 0.4%. And i also test the pre-trained weights on my data, the test results are consistent with expectations(89.9%). So i suppose the problem is not with the data. Do you have any idea why this is the case, or there are any details of the implementation I failed to  pay attention to?

**Comment by SLime1998** [comment]
it turns out it's caused by different dependencies

**Comment by hosamyousof** [comment]
@SLime1998 what do you mean by it’s caused by different dependencies, because I have the same issue. I’ve created an issue but still didn’t get an answer.

Check issue please: https://github.com/Uason-Chen/CTR-GCN/issues/36
