### ISSUE TITLE
Thank you for your great work

### ISSUE THREAD

**Issue by ChenHongBo0420** [Uason-Chen/CTR-GCN#11]
I've been reading your work and have a few questions that I'd like to ask you
1. For the equation 7, the Q in the code, somewhat like non-local block，could you tell me the difference between the two? I mean non-local is also spatio-temporal modelling of the relationship between two joints, it feels like it's just condensing time.
2. For the equation 8, you use three CTR-GCNs to add in a torch-list, so it looks like in the 2s-AGCN do, do I understand you correctly? This divides the code with ke cheng DeCoupling GCN`s point being made the same?
norm_learn_A = torch.cat([self.norm(learn_A[0:1, ...]), self.norm(learn_A[1:2, ...]), self.norm(learn_A[2:3, ...])], 0)

**Comment by Uason-Chen** [comment]
Thanks for your interest.
1. The relationship in non-local is represented as a scalar. While relationship in Q is represented as a C-dimensional vector, which is the key to achieving channel-wise topology modeling.
2. Eq. 8 shows the feature aggregation in one single CTR-GC. Specifically, CTR-GC infers a dynamic topology R_i for each feature channel and R_i is used to aggregate features in channel i (R_i x x_{:,i}), then aggregated features of each channel are concatenated to form the output feature. As for "use three CTR-GCNs to add in a torch-list", it's same with 2s-AGCN and we adopt such ensemble method to make a fair comparison with other methods, i.e., 2s-AGCN, DeCoupling GCN.

**Comment by ChenHongBo0420** [comment]
Thank you very much for your reply, it has been very enlightening for me.
But I would still like to ask about scalar and vector, I am a bit confused and would appreciate if you could elaborate on this.

**Comment by ChenHongBo0420** [comment]
By the way, how do you see a way of defining something like shift-gcn that does not require an adjacency matrix? Does it eliminate the need for an adjacency matrix for non-shared topologies? This question has been bothering me because I feel as if the concept of non-shared does not exist either in shift or 1*1 convolution. Similarly for separable convolutions in CNNs? I am not sure if I understand it correctly and would appreciate your guidance
Thank you very, very much

**Comment by Uason-Chen** [comment]
> Thank you very much for your reply, it has been very enlightening for me. But I would still like to ask about scalar and vector, I am a bit confused and would appreciate if you could elaborate on this.

In brief, non-local operation computes a attention matrix in R^{NxN} which reflects relationships between pair of joints. And Q is a tensor in R^{NxNxC} which reflects relationships between pairs of joints in each specific channel.

**Comment by Uason-Chen** [comment]
> By the way, how do you see a way of defining something like shift-gcn that does not require an adjacency matrix? Does it eliminate the need for an adjacency matrix for non-shared topologies? This question has been bothering me because I feel as if the concept of non-shared does not exist either in shift or 1*1 convolution. Similarly for separable convolutions in CNNs? I am not sure if I understand it correctly and would appreciate your guidance Thank you very, very much

Thanks for your interesting question. In the shift-gcn, taking non-local graph shift as an example, shift operation in each channel actually can be implemented by multiplying a elementary matrix. And the elementary matrix for each channel can be seen as a fixed non-shared topologies.
![image](https://user-images.githubusercontent.com/76673008/142337156-b2c55b09-ab34-45d6-8a17-8b0253709b25.png)


Specifically, the elementary matrix for the first channel is a identity matrix, and it's a circulant matrix as shown below
![image](https://user-images.githubusercontent.com/76673008/142337074-102c1ee8-6f3e-4b76-87cb-a96fe9bb798c.png)

**Comment by ChenHongBo0420** [comment]
Thank you very much for your reply, which has been a total inspiration to me.
I wish you all the best.
