### ISSUE TITLE
Understanding the inward_ori_index variable in the ntu_rgb_d.py file in the Graph folder

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [Uason-Chen/CTR-GCN#12]
Hello, thank you so much for your hard work. I am trying to understand how the inward_ori_index, the tuples of joints considered linked, were determined. 

For instance, as far as I understand these are the joint numbers (using 0-indexing):
`joint_names_dict = {0: "spine_base", 1:"spine_mid", 2: "neck", 3:"head", 4:"shoulder_left", 5:"elbow_left", 6: "wrist_left",
                    7: "hand_left", 8: "shoulder_right", 9:"elbow_right", 10:"wrist_right", 11:"hand_right",
                    12: "hip_left", 13:"knee_left", 14:"ankle_left", 15:"foot_left", 16:"hip_right", 17:"knee_right",
                    18:"ankle_right", 19: "foot_right", 20:"spine_shoulder", 21:"hand_tip_left", 22:"thumb_left", 23:"hand_tip_right",
                    24:"thumb_right"}`

What was the thought process between choosing the pairs 
```
inward_ori_index = [(1, 2), (2, 21), (3, 21), (4, 3), (5, 21), (6, 5), (7, 6),
                    (8, 7), (9, 21), (10, 9), (11, 10), (12, 11), (13, 1),
                    (14, 13), (15, 14), (16, 15), (17, 1), (18, 17), (19, 18),
                    (20, 19), (22, 23), (23, 8), (24, 25), (25, 12)]
```

**Comment by Uason-Chen** [comment]
These pairs are chosen according to the human skeleton in paper `ntu rgb+d a large scale dataset for 3d human activity analysis`
![image](https://user-images.githubusercontent.com/76673008/142190337-50552d9a-0385-4fe1-9a10-f16c22d99aed.png)

As shown in above figure, joint 21 is the centre joint. All you need to do is  traversing every joint and find its adjacent inward joint, e.g. (1, 2), (2, 21), (3, 21) ...

**Comment by JamesMcCullochDickens** [comment]
Thanks!
