### ISSUE TITLE
about implementation details

### ISSUE THREAD

**Issue by jjingli** [Uason-Chen/CTR-GCN#2]
I run your code (use default.yaml),but I didn't get as good results as your article reported.
Could you please provide the more details about your specific content of configuration file ?
Thank you !!

**Comment by Uason-Chen** [comment]
Hi, the config file contains all configurations needed to reproduce our results. There are many possible reasons for this case, such as data not being processed correctly, different versions of dependencies, etc. You can provide me the training log, and check if there is any problem with your data by testing the pre-trained model we provide.

**Comment by jjingli** [comment]
Hi,
Thanks for  your reply! I find that you fuse results of four modalities to get the best performance.But I just use joint as input to train this net.
So,I just get top1:89.32%,top5:98.28% on nturgbd60 ...
thank you very much!!

**Comment by jjingli** [comment]
> Hi, the config file contains all configurations needed to reproduce our results. There are many possible reasons for this case, such as data not being processed correctly, different versions of dependencies, etc. You can provide me the training log, and check if there is any problem with your data by testing the pre-trained model we provide.

Hi,
Thanks for  your reply! I find that you fuse results of four modalities.But I just use joint as input to train this net.
So,I just get top1:89.32%,top5:98.28% on nturgbd60 ...
thank you very much!!
