### ISSUE TITLE
Issues on "lr_decay_rate"

### ISSUE THREAD

**Issue by sayano-lee** [Uason-Chen/CTR-GCN#3]
Thanks for sharing your work, but I found the issue on hyper-param: `lr_decay_rate` in the config files and `main.py`.
I think there should be a term: `lr_decay_rate` in the yaml files, and this hyper-param should also be added to the parser in the `main.py`.

**Comment by Uason-Chen** [comment]
Thanks for your suggestion. I add the `lr_decay_rate` in both config files and `main.py`.
