### ISSUE TITLE
Is there another way to implement this api?

### ISSUE THREAD

**Issue by universea** [Uason-Chen/CTR-GCN#4]
def forward(self, x, A=None, alpha=1):
        x1, x2, x3 = self.conv1(x).mean(-2), self.conv2(x).mean(-2), self.conv3(x)
        x1 = self.tanh(x1.unsqueeze(-1) - x2.unsqueeze(-2))
        x1 = self.conv4(x1) * alpha + (A.unsqueeze(0).unsqueeze(0) if A is not None else 0)  # N,C,V,V
        **x1 = torch.einsum('ncuv,nctv->nctu', x1, x3)**

I want to use another Deeplearning framework to achieve this model, but I can't find the einsum api, can we use other normal api to replace it ?

**Comment by Uason-Chen** [comment]
You can use matrix multiplication api to replace it. `torch.einsum('ncuv,nctv->nctu', x1, x3)` equals to `torch.matmul(x3, x1.transpose(-1,-2))`.

**Comment by universea** [comment]
> You can use matrix multiplication api to replace it. `torch.einsum('ncuv,nctv->nctu', x1, x3)` equals to `torch.matmul(x3, x1.transpose(-1,-2))`.

Thank you very much!
