### ISSUE TITLE
About NTU60_CS.npz file

### ISSUE THREAD

**Issue by yumengyun** [Uason-Chen/CTR-GCN#5]
Hi, I'm very interested in your work. But I met a problem while running the code.

The problem as follow: 
FileNotFoundError: [Errno 2] No such file or directory: 'data/ntu/NTU60_CS.npz'

What is the NTU60_CS.npz file?

Best regards!

**Comment by Uason-Chen** [comment]
It's preprocessed NTU RGB+D 60 dataset with cross subject setting. It can be obtained by following commands. Detailed data preprocessing can be found in README
` cd ./data/ntu

 python get_raw_skes_data.py

 python get_raw_denoised_data.py

 python seq_transformation.py`

**Comment by yumengyun** [comment]
Thank you very much for your reply.
